services:
  - type: web
    name: jbnu-publication-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: jbnu-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /